### ISSUE TITLE
Snap/Lock functions only working when Assisted Flight is enabled

### ISSUE THREAD

**Issue by r1klz** [kennethsible/elytrapitch#3]
This is happening in version `1.3.1`, where "Assisted Flight" was introduce. It couldn't be reproduced in the previous version `1.3.0`.

Actually, I don't really know if it's a bug or not. I read your comment on #2 but didn't understand the real purpose of it. Can you explain it?

**Comment by kennethsible** [comment]
In the pull request you mentioned (#2), I disabled the keybindings for snap/lock by default with the toggle for assisted flight since those features are added functionality. I was worried that new players might accidentally lock their pitch, for example, without knowing that pitch locking was even a feature of a HUD mod. I see now how this might be confusing. I think a better solution would be to remove the toggle for assisted flight but not assign default keybindings for snap/lock, so if you want to use those features, you would need to set your own keybindings. If you think that will remove the confusion, let me know!

**Comment by r1klz** [comment]
Oh, I see now. The main purpose was to be a simple HUD mod, I'm right?
So, thinking about what you said, I think it's easier for sure to do that. But that will delete your idea on implementing *Assisted Flight*! What do you think about adding the toggle for *Assisted Flight* into "Key Binds" menu inside the game options (along with the other options) and document what it does? I think it's a more straightforward thought.

**Comment by r1klz** [comment]
I also thought about moving all the options about snapping/locking the screen to the Mod Menu like *Assisted Flight*, making it more minimalist and keeping the main idea of a simple QoL HUD, while maintaining its beautiful configuration.

**Comment by kennethsible** [comment]
I removed the assisted flight toggle and the default snap/lock keybindings (4248ded), so assisted flight is now disabled by default. If you want to use the snap/lock functionality (still called assisted flight), just assign your own keybindings. You'll see these changes in the next release (v1.4.0).
